jobs:
  deployContainerImage_aiExtensionDocker:
    if: ${{ github.repository == 'fluidattacks/ai-extension-docker' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build sorts-extension Docker image
      run: |
        docker build . --tag "ghcr.io/fluidattacks/sorts-extension:$GITHUB_SHA"
        docker push "ghcr.io/fluidattacks/sorts-extension:$GITHUB_SHA"
name: prod
on:
  push:
    branches: [main]
